version = 0.1
[default.deploy.parameters]
stack_name = "candidate2014"
resolve_s3 = false
#s3_prefix = "candidate2014"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
