name: "AWS SAM"

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - *

jobs:
  build-and-deploy-SAM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Build
        working-directory: kjell/
        run: |
          sam build --use-container
      
      - name: Deploy
        if: github.repository == 'main'
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset 