name: "AWS ECR"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build_docker_image:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Build Docker image
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
          rev=$(git rev-parse --short HEAD)
          docker build . -t app
          docker tag app ${{ secrets.AWS_ECR_URL }}/candidate2024:$rev
          docker tag app ${{ secrets.AWS_ECR_URL }}/candidate2024:latest
          
      - name: Push Docker image
        if: github.repository == 'main'
        run: |
          docker push ${{ secrets.AWS_ECR_URL }}/candidate2024:$rev
          docker push ${{ secrets.AWS_ECR_URL }}/candidate2024:latest
