name: "AWS SAM Rekognition"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  build_and_deploy_SAM:
#    runs-on: ubuntu-latest
#    env:
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      BUCKET_NAME: ${{ secrets.AWS_SAM_S3_BUCKET }}
#    
#    steps:
#      - name: Check out the repository
#        uses: actions/checkout@v3
#        
#      - name: Build and deploy
#        working-directory: kjell/
#        run: |
#          sam build --use-container
#          sam deploy

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset 