name: "AWS SAM Rekognition"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_SAM:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ secrets.AWS_SAM_S3_BUCKET }}
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Build and deploy
        working-directory: kjell/
        run: |
          sam build --use-container
          sam deploy